### ISSUE TITLE
Return condition

### ISSUE THREAD

**Issue by IanaKhitsko** [Hmelmin/diffusion#5]
https://github.com/Hmelmin/diffusion/blob/d8001d233ae1997aef8115e4869b0efdbf7a8310/src/model/Map.java#L79

return !((country.getUpperRightY()<0 || country.getUpperRightY()>9) ||
                (country.getUpperRightX()<0 || country.getUpperRightX()>9) ||
                (country.getLowerLeftY()<0 || country.getLowerLeftY()>9) ||
                (country.getLowerLeftX()<0 || country.getLowerLeftX()>9));

**Comment by Hmelmin** [comment]
Refactored
