### ISSUE TITLE
Look-like-copy-pasted methods

### ISSUE THREAD

**Issue by IanaKhitsko** [Hmelmin/diffusion#6]
https://github.com/Hmelmin/diffusion/blob/d8001d233ae1997aef8115e4869b0efdbf7a8310/src/model/Map.java#L210

these methods are pretty much similar. Can we design one, instead of four? (Do you have templates in Java? )
Or, you can at least join 'right' and 'left' methods, and 'lower' and 'higher' methods.

**Comment by Hmelmin** [comment]
Created 2 methods: for left|right and lower|upper.I need 2 different loops for these functions anyway
