### ISSUE TITLE
Copy-pasted code

### ISSUE THREAD

**Issue by IanaKhitsko** [Hmelmin/diffusion#7]
https://github.com/Hmelmin/diffusion/blob/d8001d233ae1997aef8115e4869b0efdbf7a8310/src/model/Map.java#L253-L255

at least this code can be moved to a separate method

**Comment by Hmelmin** [comment]
Moved to a separate method https://github.com/Hmelmin/diffusion/blob/861fa1f7dabe043211996ef2c8286ef0465c9268/src/model/Map.java#L242
